version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart_attendance
    ports:
      - "5432:5432"

# Run it with: docker-compose up -d
